spring.application.name=AJPD-GestionMiembros
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:mock-client-id}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_SECRET:mock-secret}
spring.security.oauth2.client.registration.google.scope=email,profile
app.security.frontend-url=${FRONTEND_URL:http://localhost:4200}
app.security.jwt-secret=${JWT_SECRET}
app.security.jwt-expiration-ms=86400000
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Optimization
spring.main.lazy-initialization=true
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
server.tomcat.threads.max=4
server.tomcat.threads.min-spare=1





